### ISSUE TITLE
Android version? (via Termux)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [viblo/pymunk#162]
I've been having a lot of fun lately integrating pymunk with [PySimpleGUI](http://www.PySimpleGUI.org).  

Here is a beginning of a game I'm working on that will be played between 2 or more players.  For 3 players, I'll use PySimpleGUIWeb so that multiple people can connect to the program.  

It currently runs on both tkinter and Remi (PySimpleGUIWeb).

You can see the tkinter version here:
https://repl.it/@PySimpleGUI/Simple-pymunk-ball-game

I want to ultimately run this code on Android using a program called Termux.  With it I'm able to pip install all of the packages I need for the web version..... except pymunk.  

Is there a way of running on Android using termux?

**Comment by viblo** [comment]
Interesting question! 
Pymunk can run on Android, at one time I made a small demo using Kivy that I managed to run on my phone after a bit of work (not published on the play store). There is a script for building it here https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/pymunk/__init__.py

I tried running termux just now, this is the first time I hear about it. Unfortunately it did not work out of the box. Right now I managed to get it to install, but it fails when running. I will continue to investigate.

**Comment by MikeTheWatchGuy** [comment]
THANK YOU SO MUCH for the quick response!!

I've tried a number of times in the past to get something running on Android, and I finally did when I make PySimpleGUIWeb.  It uses Remi which works through your browser.  

I found that Termux works GREAT with PySimpleGUIWeb and Remi.  I can pip install PySimpleGUIWeb, then run my app.  The GUI will show up in a browser.  Other people can connect to your phone and see the same browse GUI.  This is a great setup for playing games, phone to phone (or tablet).

![PSG on Android](https://user-images.githubusercontent.com/13696193/56869185-477a8480-69cb-11e9-8191-6ebca93ab4c4.jpg)

Here you can see the beginning of some kind of game.  This is how it will look in your browser on Android, assuming I can get it working there:
https://repl.it/@PySimpleGUI/Ball-Game-Web-Version

**Comment by viblo** [comment]
Ok, now I got it to install and run properly (tests passing except for doctests, but thats because they expect python2..). Im surprised it was so easy :)

I had to do a number of things:
1. install stuff with pkg `pkg install python clang python-dev libffi-dev`
2. install wheel package (this is fixed in master git branch, so next version of pymunk wont need it): `pip install wheel`
3. Install pymunk with pip with some special env variables `CFLAGS="-DANDROID=1 -fPIC -O3" LDFLAGS="-fPIC -lm -llog" pip install pymunk`

**Comment by MikeTheWatchGuy** [comment]
You're my hero!!!!

I'll try and duplicate what you managed to get running.  Termux seems pretty good for my Python programs.  Am pleased you found it easy to work with.

**Comment by MikeTheWatchGuy** [comment]
![P1320812_1](https://user-images.githubusercontent.com/13696193/56870000-9bd73180-69d6-11e9-9379-fca131c67ef6.jpg)
![P1320813_1](https://user-images.githubusercontent.com/13696193/56870001-9c6fc800-69d6-11e9-8b7a-4ee23290943a.jpg)

I ran into this error after following the 3 steps you provided.
I will check them all again to make sure I typed it right.  Sometimes it was hard to tell between a zero and an O, or an I.  I think I got it right, but maybe not.

**Comment by MikeTheWatchGuy** [comment]
I tried typing it all in again (it crashed once before so I lost the env variables).  It still crashes complaining about a missing .so file

**Comment by viblo** [comment]
Note that if you installed it once and you want to reinstall it you need to skip the pip cache, otherwise it will just reuse the compiled file. One way to do it is installing with the no cache dir option: `pip install pymunk --no-cache-dir`. 
The error in the first picture is because LDFLAGS was not set correctly.
Instead of writing it all in one long line you can also set the env variables one by one:
```
$ export CFLAGS="-DANDROID=1 -fPIC -O3" 
$ export LDFLAGS="-fPIC -lm -llog"
$ pip uninstall pymunk
$ pip install pymunk --no-cache-dir
```

**Comment by MikeTheWatchGuy** [comment]
#IT WORKS!!!!

**Comment by MikeTheWatchGuy** [comment]
![PSG On Android](https://user-images.githubusercontent.com/13696193/56870573-8fa3a200-69df-11e9-8013-5cd353b4c0a2.gif)

**Comment by viblo** [comment]
Nice! This is very cool!

Before I close this issue I will do a bit more investigation if I can make it work without the special env variables. Just need to detect that the setup is running on android somehow. I will also make a note in the installation instructions that pymunk can run on android.

**Comment by MikeTheWatchGuy** [comment]
For sure you can claim you're on Android!

Thanks for making all this happen in under 1 day.

**Comment by viblo** [comment]
Latest master branch should now work on Android with Termux without the special environment variables. (Will be included in the next release of pymunk). Closing this issue for now..

**Comment by MikeTheWatchGuy** [comment]
WOW!
Really???  No need for the sets and stuff? 

NICE!!

Thank you so much for making this happen.   It opens up all kinds of things for kids to program games that will run on their phone.
